<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5ekyfj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5ekyfj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerW5ekyfj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerW5ekyfj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerW5ekyfj\appDevDebugProjectContainer([
    'container.build_hash' => 'W5ekyfj',
    'container.build_id' => '7900a9f4',
    'container.build_time' => 1592226315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5ekyfj');
