<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF0xxbyg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF0xxbyg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF0xxbyg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF0xxbyg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerF0xxbyg\appDevDebugProjectContainer([
    'container.build_hash' => 'F0xxbyg',
    'container.build_id' => 'b70610d3',
    'container.build_time' => 1586900081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF0xxbyg');
