<?php

namespace PioneerBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{

    function findAllOrderby(){
        $query=$this->getEntityManager()
            ->createQuery("select d from PioneerBundle:Actualite d ORDER BY d.id DESC  ");
        //->setParameter('n',$val);
        //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }
}