<?php

namespace PioneerBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    function ShowCmtBlog($idB){
        $query=$this->getEntityManager()
            ->createQuery("select c from PioneerBundle:Comment c where c.actualite=:idB  ORDER BY c.point DESC  ")
            ->setParameter('idB',$idB);

        return $query->getResult();
    }

    function CountCmtBlog($idB){
        $query=$this->getEntityManager()
            ->createQuery("select count(c.id) from PioneerBundle:Comment c where c.actualite=:idB  ORDER BY c.point DESC  ")
            ->setParameter('idB',$idB);

        return $query->getSingleScalarResult();
    }

}