<?php

namespace PioneerBundle\Repository;

/**
 * EnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantRepository extends \Doctrine\ORM\EntityRepository
{
    function selectEnf($cin)
    {
        $query=$this->getEntityManager()
            ->createQuery(' Select a from PioneerBundle:Enfant a where  a.cinP=:cin')
            ->setParameter('cin',$cin);
        return $query->getResult();
    }

}