<?php

namespace PioneerBundle\Repository;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{

    function findAllOrderby(){
        $query=$this->getEntityManager()
            ->createQuery("select d from PioneerBundle:Evaluation d ORDER BY d.id DESC  ");
        //->setParameter('n',$val);
        //->setParameter('n','%'.$val.'%');
        return $query->getResult();
    }


    function AvgAbs($idAc)
    {
        dump($idAc);
        $query=$this->getEntityManager()
            ->createQuery(' Select score from PioneerBundle:Evaluation a where  a.id_ac=:idAc')
            ->setParameter('idAc',$idAc);
        dump($query->getResult());
        return $query->getResult();

    }
 function GetEvalEtudiant ($enf){
       $query=$this->getEntityManager()
         ->createQuery(' Select a from PioneerBundle:Evaluation a where  a.idE=:idE')
         ->setParameter('idE',$enf);

     return $query->getResult();
}

}