<?php

namespace PioneerBundle\Repository;

/**
 * ReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplyRepository extends \Doctrine\ORM\EntityRepository
{
    function FindLikeOrderBy(){
        $query=$this->getEntityManager()
            ->createQuery("select c from PioneerBundle:Reply c ORDER BY c.point DESC  ");
        return $query->getResult();
    }

}