transport_homepage:
    path:     /t1
    defaults: { _controller: TransportBundle:Default:index }
bus_homepage:
    path:     /bus
    defaults: { _controller: TransportBundle:Bus:afficher }
add_bus:
    path:     /add
    defaults: { _controller: TransportBundle:Bus:ajouter }
trajet_homepage:
    path:     /trajet
    defaults: { _controller: TransportBundle:Default:trajet }
Tback_homepage:
    path:     /back
    defaults: { _controller: TransportBundle:Default:back }
Transport2_homepage:
    path:     /t2
    defaults: { _controller: TransportBundle:Default:transportespace }
editdetails:
    path:     /edit/{id}
    defaults: { _controller: TransportBundle:Bus:modifier }
deletedetails:
    path:     /delete/{id}
    defaults: { _controller: TransportBundle:Bus:delete }
editdetailstr:
  path:     /edittr/{id}
  defaults: { _controller: TransportBundle:Trajet:modifiertr }
deletedetailstr:
  path:     /deletetr/{id}
  defaults: { _controller: TransportBundle:Trajet:deletetr }
afficherdetails:
    path:     /affiche
    defaults: { _controller: TransportBundle:Bus:afficher }
add_trajet:
  path:     /addtr
  defaults: { _controller: TransportBundle:Trajet:ajoutertr }
afficherdetailstr:
  path:     /affichetr
  defaults: { _controller: TransportBundle:Trajet:affichertr }
add_station:
  path:     /addst/{id}/{m}
  defaults: { _controller: TransportBundle:Station:ajouterst }
afficherdetailsst:
  path:     /affichest/{id}
  defaults: { _controller: TransportBundle:Station:afficherst }
deletedetailsst:
  path:     /deletest/{id}/{id2}
  defaults: { _controller: TransportBundle:Station:deletest }

busf:
  path:     /busf
  defaults: { _controller: TransportBundle:Busetcov:afficherf }
co:
  path:     /co
  defaults: { _controller: TransportBundle:Busetcov:afficherco }
demande:
  path:     /demande
  defaults: { _controller: TransportBundle:Busetcov:afficherdemande }
offre:
  path:     /offre
  defaults: { _controller: TransportBundle:Busetcov:afficheroffre }
afficherbuss:
  path:     /afficherbuss
  defaults: { _controller: TransportBundle:Busetcov:afficherbuss }

mobile:
  path:     /busall
  defaults: { _controller: TransportBundle:Bus:all }
mobile2:
  path:     /trajetid/{id}
  defaults: { _controller: TransportBundle:Trajet:trajetfind }
mobile55:
  path:     /trajetidzz
  defaults: { _controller: TransportBundle:Trajet:trajetfindbus }
mobile3:
  path:     /trajetall
  defaults: { _controller: TransportBundle:Trajet:all }
mobile13:
  path:     /trajetadd/{name}/{idbus}
  defaults: { _controller: TransportBundle:Trajet:trajetadd }
mobile4:
  path:     /busmobile/{id}/{name}/{capacite}/{chauffeur}
  defaults: { _controller: TransportBundle:Bus:editmobile }
mobil4:
  path:     /busmobile3/{name}/{capacite}/{chauffeur}
  defaults: { _controller: TransportBundle:Bus:addmobile }
mobile5:
  path:     /busmobile2/{id}
  defaults: { _controller: TransportBundle:Bus:deletemobile }
mobile51188:
  path:     /trajetdel/{id}
  defaults: { _controller: TransportBundle:Trajet:trajetdel }
mobile588:
  path:     /trajeteditt/{name}/{idbus}/{id}
  defaults: { _controller: TransportBundle:Trajet:trajeteditt }

mobile511288:
  path:     /stationdel/{id}
  defaults: { _controller: TransportBundle:Station:stationdel }
mobile5818:
  path:     /stationadd/{name}/{id}
  defaults: { _controller: TransportBundle:Station:stationadd}
mobile58148:
  path:     /stationall/{id}
  defaults: { _controller: TransportBundle:Station:stationall}
