back_homepage:
    path:     /index
    defaults: { _controller: BackBundle:Default:index }

admin_dashboard:
    path:     /admin
    defaults: { _controller: BackBundle:Back:index }

Email:
    path:     /email
    defaults: { _controller: BackBundle:Default:email }
