<?php

namespace rappelBundle\Repository;

/**
 * rappelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rappelRepository extends \Doctrine\ORM\EntityRepository
{
}
