<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwnsmaa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwnsmaa/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRwnsmaa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRwnsmaa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRwnsmaa\appProdProjectContainer([
    'container.build_hash' => 'Rwnsmaa',
    'container.build_id' => '7f22b262',
    'container.build_time' => 1584929231,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwnsmaa');
