<?php

namespace RecBundle\Repository;

/**
 * RecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecRepository extends \Doctrine\ORM\EntityRepository
{
}
