esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /api

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

pioneer:
    resource: "@PioneerBundle/Resources/config/routing.yml"
    prefix:   /pioneer
transport:
    resource: "@TransportBundle/Resources/config/routing.yml"
    prefix:   /transport

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications

activite:
    resource: "@activiteBundle/Resources/config/routing.yml"
    prefix:   /activite

esprit_e5e:
    resource: "@RecBundle/Resources/config/routing.yml"
    prefix:   /recaa

mail:
    resource: "@mailBundle/Resources/config/routing.yml"
    prefix:   /email
api1:
    resource: "@rappelBundle/Resources/config/routing.yml"
    prefix:   /api1
