back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

pioneer:
    resource: "@PioneerBundle/Resources/config/routing.yml"
    prefix:   /pioneer


app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
