security:
    #encoders:
        #FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        R: ROLE_ADMIN
        T: T
        P: P
       # ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: ROLE_ADMIN


    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            #user_checker: fos_user.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/registration-form-submission$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(login|register)$, role: IS_AUTHENTICATED_ANONYMOUSLY }